dataset: 'kitti'

dataset_path: '/media/wangxiyang/3448ECD748EC98BE/datasets/KITTI/kitti_tracking'
spilt: 'training'

#------------------------ Root path define ----------------------
save_path: 'results/KITTI'
eval_save_path: 'results/KITTI/data'
dets_path_3d: "data/detections/3D"
dets_path_2d: "data/detections/2D"


#------------------------Dataset spilt--------------------------
#tracking_seqs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
tracking_seqs: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]


#----------------------------Detector--------------------------
detector_2d: 'rrc'
detector_3d: 'pointrcnn'


#----------------------------Category--------------------------
#cat_list: ['Car', 'Pedestrian']
cat_list: ['Car']


#----------------------------Hyperparameter--------------------------
#If you want a better result, re-adjust the following hyperparameter
Car:
  metric_3d: iou_3d
  metric_2d: iou_2d
  max_ages: 25
  min_frames: 3
  cost_function:
      iou_2d: 0.5
      sdiou_2d: 1.1
      giou_3d: -0.2
      iou_3d: 0.01
      dist_3d: 1.1

Pedestrian:
  metric_3d: iou_3d
  metric_2d: iou_2d
  max_ages: 25
  min_frames: 3
  cost_function:
      iou_2d: 0.5
      sdiou_2d: 0.2
      giou_3d: -0.2
      iou_3d: 0.01
      dist_3d: 1.1

